### ISSUE TITLE
Unformat issue

### ISSUE THREAD

**Issue by luisfmsouza** [foretagsplatsen/numbro#169] opened 2016-05-09 19:25 UTC
When I try to unformat something like: 'STFT500', I got '500'.

Is that ok?

**Comment by BenjaminVanRyseghem** [comment] 2016-05-10 06:22
what do you expect to have?

**Comment by luisfmsouza** [comment] 2016-05-10 11:43
I think this data shouldn't be unformatted. 

Something like `STFT500` doesn't seem to me a proper input data.

**Comment by BenjaminVanRyseghem** [comment] 2016-05-10 11:46
ok :smile:

then I think your ticket is a duplicate of #154 

Do you agree? If yes, can you close this one, otherwise could you explain the difference

Thanks in advance :smile:

**Comment by luisfmsouza** [comment] 2016-05-10 11:59
I saw you guys have decided to use the semantic of ParsInt, so my point is not valid in this case.

Just to ilustrate what I had in my mind:
`
// current behavior
unformat("string 10")
>> 10

// suggested
unformat("string 10")
>> string 10
`

**Comment by BenjaminVanRyseghem** [comment] 2016-05-10 12:02
I think it's better to have

```
unformat("string 10")  // raise an error
```

:smile:

Let's discuss this point further on #154 :smile:

**Closed by BenjaminVanRyseghem** 2016-05-10 12:02 UTC
