### ISSUE TITLE
NodeJS is not properly detected

### ISSUE THREAD

**Issue by aetna-softwares** [foretagsplatsen/numbro#133] opened 2016-02-20 09:56 UTC
Numbro nodejs runtime detection use a test on process.title : 
```
 (process.title === 'node' || process.title === 'grunt')
```
But in my case it failed because the process.title is /usr/bin/nodejs

Moreover, process.title can be redefined at anytime as it is a read/write property (https://nodejs.org/api/process.html#process_process_title)

I workaround the problem by putting process.title = "node" on startup of my code

**Comment by stewart42** [comment] 2016-04-06 15:09
see #118

**Comment by BenjaminVanRyseghem** [comment] 2016-04-06 15:17
I close this issue as it's a duplicate of #118 as @stewart42 pointed out.

Feel free to join the discussion there :smile:

**Closed** 2016-04-06 21:50 UTC
